name = "snapr-api"
main = "src/index.ts"
compatibility_date = "2024-11-15"

account_id = "fba122ac756d435879872c360b2004f7"
workers_dev = true
send_metrics = true

[vars]
SUPABASE_URL = "https://asoiwonhqoesbvcilqwd.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb2l3b25ocW9lc2J2Y2lscXdkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzE4NDY4MCwiZXhwIjoyMDc4NzYwNjgwfQ.ZRpGbtMo3Gu7fRl5fe307NRHzZHt2F1nfVSjvVopDxo"

OPENAI_API_KEY = "${OPENAI_API_KEY}"
RUNWARE_API_KEY = "QBsPi4uIH4CcwpPB3M97j7qefS2g4Ntj"

CLOUDINARY_CLOUD_NAME = "drie9liyn"
CLOUDINARY_API_KEY = "213239284765294"
CLOUDINARY_API_SECRET = "WFWiMERePmsoFgelPx_nFB7wGsE"

CLOUDFLARE_R2_PUBLIC_URL = "https://fba122ac756d435879872c360b2004f7.r2.cloudflarestorage.com/snap-r"

[[r2_buckets]]
binding = "R2"
bucket_name = "snap-r"

[[queues.producers]]
queue = "snapr-jobs"
binding = "JOB_QUEUE"
