name = "snapr-gpt"
compatibility_date = "2024-10-01"
pages_build_output_dir = ".open-next"

[vars]
SUPABASE_URL = "https://asoiwonhqoesbvcilqwd.supabase.co"
SUPABASE_SERVICE_KEY = ""
OPENAI_API_KEY = ""
RUNWARE_API_KEY = ""
REPLICATE_API_KEY = ""

