name = "snapr-gpt"
main = ".open-next/server-functions/default/index.mjs"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[pages]
pages_build_output_dir = ".next"

[vars]
SUPABASE_URL = "https://asoiwonhqoesbvcilqwd.supabase.co"
SUPABASE_SERVICE_KEY = ""
OPENAI_API_KEY = ""
RUNWARE_API_KEY = ""
REPLICATE_API_KEY = ""

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "snapr-uploads"

[[queues.producers]]
queue = "image-jobs"
binding = "IMAGE_JOBS"

[[queues.consumers]]
queue = "image-jobs"
script_name = "image-jobs-consumer"
